parent=keycloak.v2
import=common/keycloak
styles=css/shofy-base.css css/shofy-login.css css/shofy-reset.css css/shofy-components.css
scripts=js/shofy-toast.js
meta=viewport==width=device-width,initial-scale=1
locales=vi,en
defaultLocale=vi
