parent=keycloak.v2
import=common/keycloak
styles=css/crm-base.css css/crm-login.css css/crm-components.css
scripts=js/crm-toast.js
meta=viewport==width=device-width,initial-scale=1
locales=en,vi
defaultLocale=en
